export const FETCH_METADATA = 'FETCH_METADATA';
export const FETCH_SEASONS = 'FETCH_SEASONS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_ITEMS = 'FETCH_ITEMS';
export const FETCH_ITEM = 'FETCH_ITEM';
export const FETCH_USER = 'FETCH_USER';

export const FETCH_FAVORITE_ITEM_IDS = 'FETCH_FAVORITE_ITEM_IDS';
export const FETCH_FAVORITE_ITEMS = 'FETCH_FAVORITE_ITEMS';
export const FETCH_USER_VOTE_ITEM_IDS = 'FETCH_USER_VOTE_ITEM_IDS';

export const LOGOUT_USER = 'LOGOUT_USER';
